template: |
  ## What's Changed

  $CHANGES

  ---
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG

categories:
  - title: Breaking Changes
    when:
      - label: breaking
  - title: Features
    when:
      - label: feature
  - title: Bug Fixes
    when:
      - label: fix
  - title: Enhancements
    when:
      - label: enhancement
  - title: Documentation
    when:
      - label: documentation
  - title: Maintenance
    when:
      - label: maintenance

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'documentation'
      - 'maintenance'
  default: patch
