template: |
  ## What's Changed

  $CHANGES

  ---
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG

categories:
  - title: Breaking Changes
    when:
      - label: breaking
    semver-increment: major
  - title: Features
    when:
      - label: feature
    semver-increment: minor
  - title: Bug Fixes
    when:
      - label: fix
    semver-increment: patch
  - title: Enhancements
    when:
      - label: enhancement
    semver-increment: minor
  - title: Documentation
    when:
      - label: documentation
    semver-increment: patch
  - title: Maintenance
    when:
      - label: maintenance
    semver-increment: patch
