import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:pantry_app/database/database_helper.dart';
import 'package:pantry_app/models/product.dart';

part 'inventory_item.freezed.dart';
part 'inventory_item.g.dart';

/// Represents a single item stored in the user's pantry.
///
/// Each [InventoryItem] corresponds to a row in the `inventory` table. Unlike
/// [Product], which stores static product information, an inventory item
/// tracks a **specific instance** of a product that the user has added,
/// including its quantity, storage location, expiry date, and optional notes.
///
/// Multiple inventory items can share the same [barcode] — for example, a user
/// may have one can of tomatoes in the pantry and another in the fridge.
///
/// ## Identity
///
/// - The [id] field is auto‑generated by SQLite (primary key, auto‑increment).
///   It is `null` for newly created items that have not yet been inserted into
///   the database. After insertion, [id] holds the row ID.
/// - The [barcode] links this item to a [Product] in the `products` table via
///   a foreign key relationship.
/// - The [inventoryId] links this item to a named inventory (pantry).
///
/// ## Defaults
///
/// Sensible defaults are provided for common fields to reduce friction when
/// adding items:
/// - [quantity] defaults to `1`.
/// - [unit] defaults to `'pcs'` (pieces).
/// - [location] defaults to `'pantry'`.
/// - [inventoryId] defaults to `1` (the default "Home" inventory).
///
/// ## Date fields
///
/// - [expiryDate] is stored in ISO 8601 format (`YYYY-MM-DD`) as a
///   human‑readable string. It may be `null` if the user does not set an
///   expiry date.
/// - [dateAdded] is an epoch timestamp (milliseconds since Unix epoch) set
///   automatically when the item is first created. It is used by
/// [DatabaseHelper.cleanupOldEntries] to remove items that haven't been
/// re‑added for the configured retention period (see the retention days
/// setting).
///
/// ## Immutability
///
/// This class uses the `freezed` package, making it **immutable**. All
/// mutating operations (e.g., changing the quantity) must be done via the
/// generated [copyWith] method, which returns a new instance.
@freezed
abstract class InventoryItem with _$InventoryItem {
  /// Constructs an [InventoryItem].
  ///
  /// Only [barcode] is required. All other fields are either optional
  /// or have sensible defaults.
  const factory InventoryItem({
    /// The barcode of the product (e.g. EAN‑13, UPC).
    ///
    /// This is a foreign key referencing [Product.barcode] and must match an
    /// existing product in the `products` table (or be added to it).
    required String barcode,

    /// The auto‑generated primary key from the database.
    ///
    /// Set to `null` for items that have not yet been inserted. After
    /// [DatabaseHelper.insertInventoryItem] returns, the generated ID is
    /// available in the returned integer (the caller should update this field
    /// if needed).
    int? id,

    /// The quantity of the item, expressed in the given [unit].
    ///
    /// The value is stored as a [double] to support fractional quantities
    /// (e.g., `0.5` for half a pack). Defaults to `1`.
    @Default(1) double quantity,

    /// The unit of measurement for [quantity].
    ///
    /// Common values: `'pieces'`, `'g'`, `'kg'`, `'ml'`, `'L'`.
    /// Defaults to `'pieces'`.
    @Default('pieces') String unit,

    /// The expiry date in ISO 8601 format (`YYYY-MM-DD`).
    ///
    /// May be `null` if the user has not set an expiry date. When present,
    /// the date is treated as the last day the item is safe to consume
    /// (inclusive).
    ///
    /// The home screen uses this value to group items into expired /
    /// expiring soon / good categories.
    @JsonKey(name: 'expiry_date') String? expiryDate,

    /// The storage location of the item.
    ///
    /// Common values: `'pantry'`, `'fridge'`, `'freezer'`.
    /// Defaults to `'pantry'`.
    @Default('pantry') String location,

    /// Optional free‑form notes about this item.
    String? notes,

    /// Epoch timestamp (milliseconds since Unix epoch) of when the item
    /// was first added.
    ///
    /// Set automatically when the user creates the item. Used by the
    /// database cleanup routine to purge old entries after 60 days.
    @JsonKey(name: 'date_added') int? dateAdded,

    /// The ID of the inventory (pantry) this item belongs to.
    ///
    /// This is a foreign key referencing the `inventories` table.
    /// Defaults to `1` (the default "Home" inventory).
    @JsonKey(name: 'inventory_id') @Default(1) int inventoryId,
  }) = _InventoryItem;

  /// Creates an [InventoryItem] from a JSON map.
  ///
  /// The map is expected to contain the keys `expiry_date`, `date_added`, and
  /// `inventory_id` (as configured by the [JsonKey] annotations). This
  /// factory is used when deserializing data from the database (via the raw
  /// row map) or from API responses.
  factory InventoryItem.fromJson(Map<String, dynamic> json) =>
      _$InventoryItemFromJson(json);
}
