#!/usr/bin/env bash
set -euo pipefail

OFF_USER_ID=${1:-}
OFF_PASSWORD=${2:-}
CONTACT_EMAIL=${3:-}
USE_OFF_STAGING=${4:-false}
FEEDBACK_TOKEN=${5:-}
ANDROID_STORE_PASSWORD=${6:-}
ANDROID_KEY_PASSWORD=${7:-}
ANDROID_KEY_ALIAS=${8:-}

cat >.env <<EOF
OFF_USER_ID=${OFF_USER_ID}
OFF_PASSWORD=${OFF_PASSWORD}
CONTACT_EMAIL=${CONTACT_EMAIL}
USE_OFF_STAGING=${USE_OFF_STAGING}
FEEDBACK_TOKEN=${FEEDBACK_TOKEN}
EOF

if [ -n "${ANDROID_STORE_PASSWORD}" ]; then
	cat >>.env <<EOF
ANDROID_STORE_PASSWORD=${ANDROID_STORE_PASSWORD}
ANDROID_KEY_PASSWORD=${ANDROID_KEY_PASSWORD}
ANDROID_KEY_ALIAS=${ANDROID_KEY_ALIAS}
EOF
fi

echo "Injected .env (${#OFF_USER_ID} chars user, ${#OFF_PASSWORD} chars password)"
