#!/usr/bin/env bash
set -euo pipefail

OFF_USER_ID=${1:-}
OFF_PASSWORD=${2:-}
CONTACT_EMAIL=${3:-}
USE_OFF_STAGING=${4:-false}
FEEDBACK_TOKEN=${5:-}

cat >.env <<EOF
OFF_USER_ID=${OFF_USER_ID}
OFF_PASSWORD=${OFF_PASSWORD}
CONTACT_EMAIL=${CONTACT_EMAIL}
USE_OFF_STAGING=${USE_OFF_STAGING}
FEEDBACK_TOKEN=${FEEDBACK_TOKEN}
EOF

echo "Injected .env (${#OFF_USER_ID} chars user, ${#OFF_PASSWORD} chars password)"
