name: Build

on:
  push:
    branches:
      - main

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@3db98c0363e2fa5df3e1c4c471777a7c10b24cc9

  testing:
    name: Run ${{ matrix.category }} testing
    needs: security_hardening
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category:
          - static
          - unit
          - widget
      fail-fast: false
    steps:
      - name: Clone the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          path: code
      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2  # v2.23.0
        with:
          channel: stable
          cache: true
      - name: Get Flutter packages
        run: flutter pub get
        working-directory: code
      - name: Inject environment
        working-directory: code
        env:
          OFF_USER_ID: ${{ secrets.OFF_USER_ID }}
          OFF_PASSWORD: ${{ secrets.OFF_PASSWORD }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          ./scripts/inject_env.sh \
            "${OFF_USER_ID:-}" \
            "${OFF_PASSWORD:-}" \
            "${CONTACT_EMAIL:-pantry-app@example.com}" \
            "false"
      - name: Analyze Flutter
        if: matrix.category == 'static'
        run: flutter analyze --fatal-infos --fatal-warnings
        working-directory: code
      - name: Run Flutter ${{ matrix.category }} tests
        if: matrix.category != 'static'
        run: >
          flutter test --no-pub --concurrency=2 --coverage
          --coverage-path=./coverage/lcov.${{ matrix.category }}.info
          ${{ matrix.category == 'unit' && 'test/config_test.dart test/database test/models test/providers test/services test/utils' || 'test/widgets test/screens' }}
        working-directory: code
      - name: Upload code coverage to GitHub
        if: matrix.category != 'static'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: code-coverage-${{ matrix.category }}
          path: code/coverage/lcov.${{ matrix.category }}.info

  build:
    name: Build ${{ matrix.build-type }} ${{ matrix.package-type }}
    needs: testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [debug, release]
        package-type: [apk, appbundle]
      fail-fast: false
    steps:
      - name: Clone the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          path: code
      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2  # v2.23.0
        with:
          channel: stable
          cache: true
      - name: Get Flutter packages
        run: flutter pub get
        working-directory: code
      - name: Inject environment
        working-directory: code
        env:
          OFF_USER_ID: ${{ secrets.OFF_USER_ID }}
          OFF_PASSWORD: ${{ secrets.OFF_PASSWORD }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          ./scripts/inject_env.sh \
            "${OFF_USER_ID:-}" \
            "${OFF_PASSWORD:-}" \
            "${CONTACT_EMAIL:-pantry-app@example.com}" \
            "false"
      - name: Build ${{ matrix.build-type }} ${{ matrix.package-type }}
        run: >
          flutter build ${{ matrix.package-type }}
          --${{ matrix.build-type }}
          ${{ matrix.build-type == 'release' && '--obfuscate --split-debug-info=./debug-info --extra-gen-snapshot-options=--strip' || '' }}
        working-directory: code
      - name: Upload APK
        if: matrix.package-type == 'apk'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ matrix.build-type }}-apk
          path: code/build/app/outputs/flutter-apk/app-${{ matrix.build-type }}.apk
          retention-days: 90
      - name: Upload AAB
        if: matrix.package-type == 'appbundle'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ matrix.build-type }}-aab
          path: code/build/app/outputs/bundle/${{ matrix.build-type }}/app-${{ matrix.build-type }}.aab
          retention-days: 90
      - name: Upload debug symbols
        if: matrix.build-type == 'release' && matrix.package-type == 'apk'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release-debug-info
          path: code/debug-info/
          retention-days: 90

  publish:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Draft release
        id: release-drafter
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          path: artifacts
          pattern: '*-*'
          merge-multiple: true
      - name: Upload assets to release
        run: |
          gh release upload "${{ steps.release-drafter.outputs.tag_name }}" artifacts/* --repo "$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
