name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static:
    name: Run static testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: code
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
        working-directory: code
      - run: dart format --output=none --set-exit-if-changed lib/
        working-directory: code
      - run: dart analyze lib/
        working-directory: code

  unit:
    name: Run unit testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: code
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
        working-directory: code
      - run: flutter test --no-pub --concurrency=2 test/ || true
        working-directory: code

  widget:
    name: Run widget testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: code
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
        working-directory: code
      - run: flutter test --no-pub --concurrency=2 test/ || true
        working-directory: code

  build_debug_apk:
    name: Build debug apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: code
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
        working-directory: code
      - run: flutter build apk --debug
        working-directory: code