name: Patrol E2E

on:
  schedule:
    - cron: 0 3 * * 0
  workflow_dispatch:

permissions:
  contents: read

jobs:
  patrol_e2e:
    name: Run Patrol E2E tests
    runs-on: macos-latest
    strategy:
      matrix:
        api-level:
          - 34
        target:
          - google_apis
        arch:
          - x86_64
    steps:
      - name: Clone the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup Flutter
        uses: subosito/flutter-action@e14214cc42435fc0c2609c5e614a5e63a2fcd6f5  # v2.21.0
        with:
          channel: stable
          cache: true
      - name: Get Flutter packages
        run: flutter pub get
      - name: Setup Android SDK
        uses: android-actions/setup-android@e14e7e5b6cea0b4e56862d4ef4b7a605e50a8cb6  # v2
      - name: AVD cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}
      - name: Create AVD and run emulator
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b29cabeeeb7cec4612ac  # v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: echo "AVD ready"
      - name: Run emulator
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b29cabeeeb7cec4612ac  # v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb wait-for-device
            flutter test --no-pub --concurrency=2 integration_test/
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: patrol-e2e-results
          path: |
            build/patrol/
            build/app/outputs/flutter-apk/
          retention-days: 14
          if-no-files-found: warn
